default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: postgres
  username: emilykochi

test:
  <<: *default
  encoding: unicode
  database: emilykochi
  username: emilykochi

production:
  <<: *default