development:
  adapter: postgresql
  encoding: unicode
  database: crowdpublishtvdb_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: crowdpublishtvdb_production
  pool: 5
  username: 
  password:
