# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

default: &default
 adapter: postgresql
 pool: 5
 timeout: 5000

development:
 <<: *default
 encoding: unicode
 database: template1
 username: cjadams
 host: localhost
 port: 5433

test:
 <<: *default
 encoding: unicode
 database: cjadams
 username: cjadams
 host: localhost
 port: 5433
 