default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: dev
  username: jason
  
test:
  <<: *default
  encoding: unicode
  database: test
  username: jason

production:
  <<: *default
